name: Main Workflow
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
    - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarScanner Install
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"ddogadkiney_csharp-netcore-sca-02" /o:"ddogadkiney" /d:sonar.login=11107f0ab88fd2f5827458b9c6fb400205b136c3 /d:sonar.host.url=https://sonarcloud.io
          dotnet build src/NopCommerce.sln
          dotnet sonarscanner end /d:sonar.login=11107f0ab88fd2f5827458b9c6fb400205b136c3
